remote_theme: LeNPaul/Lagrange

title: "Wuke’s rabbit hole"
description: "散散漫漫的树洞"
url: "https://qiqiwuek.github.io"
baseurl: "/blog"

author: "QiqiWuek"
avatar: "/images/carter.jpg"
background: "/images/2023.jpeg"

plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

paginate: 6                 # 首页每页 6 篇
paginate_path: "/page:num"  # 翻页路径 /blog/page2 ...

markdown: kramdown
kramdown:
  parse_block_html: true



 # 怎么显示 图片 ？  还有什么意见？ post 页面怎么做？
