remote_theme: LeNPaul/Lagrange

title: "QiqiWuek’s Reading Notes"
description: "Reading & Writing"
url: "https://qiqiwuek.github.io"
baseurl: "/read_notes"

author: "QiqiWuek"
avatar: "/images/carter.jpg"
background: "/images/cover.jpeg"

navigation:
  - title: Home
    url: /
  - title: 2023 Notes
    url: /review/2023_notes/
  - title: 2024 Notes
    url: /review/2024_notes/
  - title: 2025 Notes
    url: /review/2025_notes/
  - title: About
    url: /about/

social_links:
  - name: GitHub
    url: https://github.com/qiqiwuek

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme