remote_theme: LeNPaul/Lagrange

title: "QiqiWuek’s Blog"
description: "Reading & Writing"
url: "https://qiqiwuek.github.io"
baseurl: "/blog"

author: "QiqiWuek"
avatar: "/images/carter.jpg"
background: "/images/cover.jpeg"

plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap



 # 怎么显示 图片 ？  还有什么意见？ post 页面怎么做？
