remote_theme: LeNPaul/Lagrange

title: "QiqiWuek’s Reading Notes"
description: "Reading & Writing (2023–2025)"
lang: zh-CN
url: "https://qiqiwuek.github.io"
baseurl: "/read_notes"

author:
  name: "QiqiWuek"
  bio: "Notes in English & Chinese. Reading, writing, and reflections."
  avatar: "/images/carter.jpg"      # ✅ 头像
background: "/images/cover.jpeg"  # ✅ 背景封面

theme_color: "#E9E9E9"
highlight_color: "#7FB77E"
show_excerpts: true

navigation:
  - title: Home
    url: /
  - title: 2023 Notes
    url: /review/2023_notes/
  - title: 2024 Notes
    url: /review/2024_notes/
  - title: 2025 Notes
    url: /review/2025_notes/
  - title: About
    url: /about/

social_links:
  - name: GitHub
    url: https://github.com/qiqiwuek

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme